name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito

    steps:
      - name: Working dir
        id: step_1
        run: ls -al

      - name: Hola Mundo
        run: echo "Hola Mundo"

      - name: Action
        uses: actions/checkout@v4

      - name: Working dir after action
        run: ls -al

      - name: Generar Archivo
        run:
          echo "Archivo prueba, hola" >> test.log

      - name: Subir Archivo
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log



  second_job:
    if: ${{github.ref == 'refs/heads/develop'}}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  third_job:
    runs-on: ubuntu-latest
    needs: first_job

    steps:
      - name: Descargar Archivo
        uses: actions/download-artifact@v4
        with:
          name: archivo-test

      - name: Cat file
        run: cat test.log